[tool.poetry]
name = "tlack"
version = "0.1.0"
description = ""
authors = ["arael <jonasg@umich.edu>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
PyTermGUI = "^7.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
